CREATE DATABASE IF NOT EXISTS txlab_billing;
USE txlab_billing;

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(100) NOT NULL
) ENGINE=InnoDB;
